### ISSUE TITLE
MantaOSC on Linux does not find attached manta

### ISSUE THREAD

**Issue by LFSaw** [ssfrr/libmanta#32]
successfully compiled MantaOSC on an (arch-)linux machine, however, it seems that the system is unable to find the connected manta.

```
$ dmesg
[ 1646.955437] usb 1-3.1: new full-speed USB device number 8 using s5p-ehci
[ 1647.063680] usb 1-3.1: New USB device found, idVendor=2424, idProduct=2424
[ 1647.064994] usb 1-3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1647.072300] usb 1-3.1: Product: Manta
[ 1647.076136] usb 1-3.1: Manufacturer: Snyderphonics
[ 1647.080687] usb 1-3.1: SerialNumber: 47
[ 1647.087783] hid-generic 0003:2424:2424.0004: hiddev0,hidraw0: USB HID v1.11 Device [Snyderphonics Manta] on usb-s5p-ehci-3.1/input0
```

```
$ ./MantaOSC 47
Could not find an attached Manta. Retrying...
Could not find an attached Manta. Retrying...
Could not find an attached Manta. Retrying...
```

**Comment by kroaton** [comment]
Hi,

I just moved over from Lubuntu to Ubuntu and I'm getting the same error when using PureData.

I've tried all of the suggestions from the Readme file, I've googled and tried everything I could find but nonetheless, no Manta in sight.
8
My Manta's serial number is 112 and in the terminal window I guess it's got to be device 18, 2424:2424

What else can I do/try other than running a variant of "sudo pd" (does not work on the latest Ubuntu versions) ?

Cheers and sorry if I'm being an annoying Linux noobie.

![screenshot from 2018-03-07 23-51-58](https://user-images.githubusercontent.com/6411688/37120253-8b4646a6-2262-11e8-88bd-07596f1d1328.png)

**Comment by ssfrr** [comment]
Can you try with the command-line MantaOSC application? That way we can rule out some weird PD issue.

**Comment by kroaton** [comment]
Running lsusb as a user vs root shows very different information about the Manta usb device, so by default only root has read access to the Manta. It's weird that udev rules don't make it work though.

![screenshot from 2018-03-08 00-33-10](https://user-images.githubusercontent.com/6411688/37123337-8b300f9e-226c-11e8-9ed7-4607c9e27d34.png)
![screenshot from 2018-03-08 00-33-29](https://user-images.githubusercontent.com/6411688/37123338-8b4fe8be-226c-11e8-8be4-5596c0626f3a.png)

**Comment by ssfrr** [comment]
Glad things seem to be in a workable state!

It seems like there are a couple of issues here:

1. Recent versions of Ubuntu seem to have changed something about udev handling so the instructions no longer work.
2. You're seeing an issue with the PD object with respect to it sometimes spitting out weird data.
3. You are/were having trouble running the MantaOSC application, though it seemed to build correctly.

If (2) and (3) are still issues please file them as separate issues and I'll try to help.

For (1) I unfortunately don't have a recent Ubuntu machine to troubleshoot on. I'll send a message to the mailing list to see if anyone else is using Ubuntu and has a working setup. Can you list the exact Ubuntu version you're using?
