### ISSUE TITLE
max value of slider is 65536, while incoming value only seems to be 12-bit

### ISSUE THREAD

**Issue by sensestage** [ssfrr/libmanta#37]
This causes a jump of ca. 4089 near the end to 65536 at the end.

**Comment by sensestage** [comment]
This seems to be the value sent when the touching is left.
It would be nicer to have separate message sent that the slider is no longer touched.

**Comment by ssfrr** [comment]
Valid slider values go from 0-4095, and 65536 (0xffff) is used as a value to mean it's not being touched.

Agreed that it's not the most discoverable API, and it could be easier in some cases to send a flag and have applications figure out what they want to do with it. This particular feature is a pretty light wrapper from what the firmware sends over USB, and it also works well when you're sending the value over a channel that expects simple numbers.

That said, I don't think that is a big enough win to warrant either breaking current applications or maintaining two different ways to do it with backwards compatibility.

**Comment by spiricom** [comment]
i agree
