### ISSUE TITLE
"manta.pd_linux: can't load library" in PureData

### ISSUE THREAD

**Issue by kroaton** [ssfrr/libmanta#45]
Hi, 

After following the instructions (had to also do sudo apt-get install libusb-1.0-0-dev because it was missing from Lubuntu) and compiling the PureData object with flext, I can't get it to load inside of Pd 0.48.0

No error messages popped up during compiling, I've set the proper paths in PD, I've tried creating a new PureData project with the compiled external object in the same folder but all I'm getting is this error message in the console.

I am absolutely stuck.

Any suggestions or binaries you could share?
Cheers.

- my compiled object 

[manta.pd_linux.tar.gz](https://github.com/ssfrr/libmanta/files/1714642/manta.pd_linux.tar.gz)

**Comment by spiricom** [comment]
I'm not sure! Any ideas, Spencer?

---------- Forwarded message ----------

**Comment by kroaton** [comment]
Maybe the Startup variable should be set to something other than "manta" ?

**Comment by ssfrr** [comment]
A couple things to check:

1. Make sure your paths in PD are set up correctly - can PD find other externals that are placed in the same directory where you're putting `manta.pd_linux`?
2. did you try the released builds?

**Comment by kroaton** [comment]
1. PD can find other externals without problems.

2. What released builds? I didn't see any other than the very old ones on the Snyderphonics website.

**Comment by ssfrr** [comment]
There are builds in the `releases` folder of the repo. They are indeed pretty old but there haven't been new features added since then, so unless PD has introduced incompatibilities since then they should still work.

**Comment by kroaton** [comment]
Got it all working with the builds from the release folder. Cheers.
